//ADMIN:update password
PATCH http://localhost:8080/api/user/settings/password
Content-Type: application/json
authorization: {{token}}


{
  "oldPassword":"1999224492",
  "newPassword":"2020224492",
  "confirmNewPassword": "2020224492"
}

###
//ADMIN:delete tutor
DELETE http://localhost:8080/api/admin/tutor/2
Accept: application/json
authorization: {{token}}


###
//ADMNI:add student
POST http://localhost:8080/api/admin/student
Content-Type: application/json
authorization: {{token}}

{
  "number": 20200000,
  "name": "Qrter"
}

###
//ADMNI:add tutor
POST http://localhost:8080/api/admin/tutor
Content-Type: application/json
authorization: {{token}}

{
  "number": 202002,
  "name": "LiLi"
}

###
//ADMIN:login
POST http://localhost:8080/api/login
Content-Type: application/json

{
  "name": "LANER",
  "password": 1999224492
}

> {% client.global.set("token", response.headers.valueOf("authorization")); %}

###
